# Generated by Django 5.2.3 on 2025-06-25 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountNumber_fund', to='core.fund')),
            ],
        ),
        migrations.CreateModel(
            name='BankRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asOf', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dateReceived', models.DateTimeField()),
                ('remarks', models.CharField(max_length=255)),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankRecon_accountNumber', to='bankrecon.accountnumber')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankRecon_office', to='core.office')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankReconReceived_employee', to='core.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankReconSender_employee', to='core.employee')),
            ],
        ),
    ]
