# Generated by Django 5.2.3 on 2025-06-24 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(verbose_name=255)),
                ('lastname', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundName', models.CharField(verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(verbose_name=100)),
                ('officeLocation', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankRecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=24)),
                ('asOf', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dateReceived', models.DateTimeField()),
                ('remarks', models.CharField(max_length=255)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankReconReceived_employee', to='bankrecon.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankReconSender_employee', to='bankrecon.employee')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankRecon_fund', to='bankrecon.fund')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankRecon_office', to='bankrecon.office')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='bankrecon.position'),
        ),
    ]
